# Generated by Django 4.1.4 on 2022-12-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='descrption',
            new_name='description',
        ),
    ]
